"""
constants.py - Central store for all lookup dictionaries and mappings used across the pipeline.

v2 — Major expansion:
  SKILLS_DB   : ~850 skills (was ~180)
  SKILL_SYNONYMS: ~320 mappings (was ~60)
  ROLES       : ~65 roles (was ~25)
"""

# ──────────────────────────────────────────────────────────────────────────────
# SKILLS DATABASE
# ──────────────────────────────────────────────────────────────────────────────
SKILLS_DB = [

    # ── Programming Languages ─────────────────────────────────────────────────
    "python", "java", "javascript", "typescript", "golang", "go", "rust",
    "c++", "c#", "c", "kotlin", "swift", "scala", "matlab", "ruby", "php",
    "r", "perl", "haskell", "elixir", "dart", "julia", "vba", "cobol",
    "fortran", "assembly", "groovy", "clojure", "f#", "ocaml", "erlang",
    "lua", "objective-c", "pascal", "delphi", "abap", "apex", "solidity",
    "move", "zig", "nim", "crystal", "d", "ada", "prolog", "scheme",
    "racket", "smalltalk", "tcl", "actionscript", "coffeescript", "purescript",
    "elm", "reason", "rescript", "gleam", "ballerina",
    "node.js", "nodejs", "node",

    # ── Web & API Frameworks ──────────────────────────────────────────────────
    "fastapi", "flask", "django", "express", "express.js", "spring boot", "spring",
    "spring mvc", "spring security", "spring data", "spring cloud",
    "rest api", "restful api", "graphql", "grpc", "websocket", "http",
    "soap", "openapi", "swagger", "api gateway",
    "react", "react.js", "next.js", "vue.js", "vue", "angular", "svelte",
    "sveltekit", "nuxt.js", "gatsby", "remix", "astro", "qwik",
    "html", "html5", "css", "css3", "sass", "scss", "less",
    "tailwindcss", "tailwind", "bootstrap", "material ui", "mui",
    "chakra ui", "ant design", "shadcn", "radix ui", "headless ui",
    "jquery", "backbone.js", "ember.js", "preact", "solid.js",
    "web components", "stencil", "lit",
    "fastify", "koa", "hapi", "nestjs", "nest.js", "adonis.js",
    "laravel", "symfony", "codeigniter", "yii", "cakephp", "slim",
    "rails", "sinatra", "hanami",
    "asp.net", "asp.net core", ".net", ".net core", ".net framework",
    "blazor", "maui", "xamarin",
    "gin", "echo", "fiber", "chi",
    "actix", "axum", "rocket", "warp",
    "ktor", "micronaut", "quarkus", "helidon",
    "phoenix", "plug",
    "tornado", "aiohttp", "sanic", "starlette", "litestar",
    "htmx", "alpine.js",
    "redux", "zustand", "mobx", "recoil", "jotai", "valtio", "pinia",
    "react query", "tanstack query", "swr", "apollo client",
    "webpack", "vite", "esbuild", "rollup", "parcel", "turbopack",
    "babel", "swc", "oxc",

    # ── Databases & Storage ───────────────────────────────────────────────────
    "sql", "nosql", "mysql", "postgresql", "postgres", "mongodb", "sqlite",
    "oracle", "oracle db", "mssql", "sql server", "mariadb", "cockroachdb",
    "planetscale", "neon", "supabase",
    "redis", "memcached", "elasticsearch", "opensearch", "solr",
    "cassandra", "dynamodb", "firestore", "firebase",
    "neo4j", "arangodb", "tigergraph", "janusgraph",
    "graph database", "vector database", "time series database",
    "qdrant", "pinecone", "weaviate", "chroma", "milvus", "pgvector",
    "faiss", "annoy", "hnswlib",
    "influxdb", "timescaledb", "questdb",
    "clickhouse", "druid", "apache druid", "doris", "starrocks",
    "hbase", "bigtable", "spanner",
    "couchdb", "couchbase", "ravendb",
    "db2", "sybase", "teradata",
    "prisma", "typeorm", "sequelize", "sqlalchemy", "drizzle",
    "hibernate", "jpa", "jdbc",
    "mongoose", "motor",
    "redis cache", "distributed cache",

    # ── Data & Analytics ──────────────────────────────────────────────────────
    "excel", "google sheets", "tableau", "power bi", "looker", "looker studio",
    "metabase", "superset", "apache superset", "grafana", "kibana",
    "dbt", "dbt core", "dbt cloud",
    "data analysis", "data analytics", "data visualization", "data modeling",
    "data wrangling", "data cleaning", "data quality", "data governance",
    "data catalog", "data lineage", "data mesh", "data fabric",
    "statistics", "probability", "statistical modeling", "statistical analysis",
    "a/b testing", "hypothesis testing", "experimentation", "causal inference",
    "regression analysis", "classification", "clustering", "dimensionality reduction",
    "pandas", "numpy", "matplotlib", "seaborn", "plotly", "scipy",
    "statsmodels", "sympy", "networkx", "geopandas",
    "polars", "dask", "modin", "vaex", "cudf",
    "r shiny", "ggplot2", "tidyverse", "dplyr", "tidyr", "lubridate",
    "jupyter", "jupyter notebook", "jupyterlab", "google colab", "databricks notebooks",
    "business intelligence", "bi", "olap", "etl", "elt",
    "sql analytics", "window functions", "cte",
    "excel vba", "power query", "power pivot",

    # ── Data Engineering & Big Data ───────────────────────────────────────────
    "spark", "apache spark", "pyspark", "spark sql", "spark streaming",
    "hadoop", "hdfs", "mapreduce", "yarn",
    "hive", "hive sql", "impala", "presto", "trino", "athena",
    "kafka", "apache kafka", "kafka streams", "kafka connect", "ksqldb",
    "airflow", "apache airflow", "prefect", "dagster", "mage", "metaflow",
    "luigi", "argo workflows", "temporal",
    "databricks", "databricks delta", "delta lake", "apache iceberg", "apache hudi",
    "snowflake", "redshift", "bigquery", "synapse", "azure synapse",
    "data pipeline", "data warehouse", "data lake", "data lakehouse",
    "streaming", "batch processing", "real-time processing", "event streaming",
    "flink", "apache flink", "apache beam", "dataflow",
    "nifi", "apache nifi", "fivetran", "airbyte", "stitch",
    "dbt", "great expectations", "soda",
    "medallion architecture", "lambda architecture", "kappa architecture",

    # ── Machine Learning & AI ─────────────────────────────────────────────────
    "machine learning", "deep learning", "nlp", "natural language processing",
    "computer vision", "reinforcement learning", "generative ai", "gen ai",
    "supervised learning", "unsupervised learning", "semi-supervised learning",
    "self-supervised learning", "transfer learning", "meta-learning", "few-shot learning",
    "zero-shot learning", "multi-task learning", "federated learning",
    "scikit-learn", "sklearn",
    "tensorflow", "keras", "pytorch", "torch", "jax", "flax", "haiku",
    "xgboost", "lightgbm", "catboost", "gradient boosting",
    "random forest", "decision tree", "svm", "support vector machine",
    "neural network", "cnn", "rnn", "lstm", "gru", "transformer",
    "attention mechanism", "self-attention", "multi-head attention",
    "hugging face", "transformers", "diffusers", "accelerate", "datasets",
    "bert", "roberta", "gpt", "gpt-2", "gpt-3", "gpt-4", "t5", "bart", "xlnet",
    "llama", "mistral", "gemma", "phi", "falcon", "bloom",
    "llm", "llms", "large language model", "large language models",
    "langchain", "langgraph", "llamaindex", "llama index",
    "embeddings", "word embeddings", "sentence embeddings", "vector embeddings",
    "rag", "retrieval augmented generation", "semantic search", "vector search",
    "fine-tuning", "lora", "qlora", "peft", "rlhf", "dpo", "instruction tuning",
    "prompt engineering", "prompt tuning", "chain of thought", "few-shot prompting",
    "stable diffusion", "dall-e", "midjourney", "image generation",
    "object detection", "yolo", "yolov8", "detectron2", "mmdetection",
    "image segmentation", "pose estimation", "ocr", "optical character recognition",
    "speech recognition", "text to speech", "asr", "tts",
    "recommendation system", "collaborative filtering", "content-based filtering",
    "anomaly detection", "time series forecasting", "forecasting",
    "mlflow", "weights and biases", "wandb", "neptune", "comet",
    "kubeflow", "mlops", "model deployment", "model serving", "model monitoring",
    "feature engineering", "feature store", "hyperparameter tuning",
    "cross-validation", "model evaluation", "model interpretability",
    "explainable ai", "xai", "shap", "lime", "grad-cam",
    "triton inference server", "torchserve", "bentoml", "seldon", "kserve",
    "openai", "anthropic", "cohere", "ai21", "groq",
    "langsmith", "phoenix", "ragas",
    "spacy", "nltk", "gensim", "fasttext", "word2vec", "glove",
    "opencv", "pillow", "imageio", "albumentations",
    "gymnasium", "stable baselines", "ray rllib",

    # ── Cloud & DevOps ────────────────────────────────────────────────────────
    "aws", "amazon web services", "azure", "microsoft azure", "gcp", "google cloud",
    "oracle cloud", "ibm cloud", "alibaba cloud", "digitalocean", "linode",
    "cloudflare", "vercel", "netlify", "render", "railway", "fly.io",
    "ec2", "s3", "rds", "lambda", "ecs", "eks", "fargate", "sagemaker",
    "glue", "step functions", "sqs", "sns", "kinesis", "cloudwatch",
    "cloudfront", "route53", "vpc", "iam", "cognito",
    "azure vm", "azure blob", "azure functions", "azure devops",
    "azure kubernetes service", "aks", "azure active directory", "aad",
    "gke", "cloud run", "cloud functions", "pub/sub", "cloud storage",
    "cloud build", "artifact registry",
    "docker", "docker compose", "dockerfile", "container",
    "kubernetes", "k8s", "helm", "kustomize", "istio", "linkerd",
    "openshift", "rancher", "k3s", "minikube",
    "terraform", "terraform cloud", "opentofu",
    "ansible", "chef", "puppet", "saltstack",
    "pulumi", "cdk", "cloudformation", "arm templates", "bicep",
    "github actions", "github", "gitlab", "gitlab ci", "bitbucket",
    "jenkins", "circleci", "travis ci", "teamcity", "bamboo",
    "ci/cd", "continuous integration", "continuous delivery", "continuous deployment",
    "argocd", "flux", "gitops",
    "linux", "ubuntu", "centos", "rhel", "debian", "alpine",
    "bash", "shell", "shell scripting", "zsh", "fish",
    "powershell", "batch scripting",
    "git", "git flow", "trunk based development",
    "serverless", "serverless framework",
    "cloud functions", "azure functions", "lambda",
    "monitoring", "observability", "logging", "tracing",
    "prometheus", "grafana", "alertmanager",
    "datadog", "new relic", "dynatrace", "splunk", "elastic stack", "elk stack",
    "opentelemetry", "jaeger", "zipkin",
    "nginx", "apache httpd", "caddy", "traefik", "haproxy",
    "load balancing", "auto scaling", "high availability",
    "disaster recovery", "backup", "site reliability engineering",
    "sre", "platform engineering", "infrastructure as code", "iac",
    "cost optimization", "finops",

    # ── Testing & QA ──────────────────────────────────────────────────────────
    "unit testing", "integration testing", "end-to-end testing", "e2e testing",
    "system testing", "regression testing", "smoke testing", "load testing",
    "performance testing", "stress testing", "security testing",
    "test automation", "manual testing",
    "pytest", "unittest", "nose", "hypothesis",
    "junit", "testng", "mockito", "powermock",
    "jest", "vitest", "mocha", "chai", "sinon", "supertest",
    "rspec", "minitest",
    "nunit", "xunit", "mstest",
    "selenium", "selenide", "webdriver", "appium",
    "cypress", "playwright", "puppeteer", "webdriverio",
    "k6", "jmeter", "gatling", "locust", "artillery",
    "postman", "insomnia", "bruno", "rest assured",
    "test driven development", "tdd", "behaviour driven development", "bdd",
    "cucumber", "gherkin", "behave",
    "sonarqube", "coverage", "code quality", "linting",
    "eslint", "prettier", "pylint", "flake8", "black", "ruff",
    "static analysis", "code review",
    "contract testing", "pact",
    "chaos engineering", "fault injection",

    # ── Security ──────────────────────────────────────────────────────────────
    "cybersecurity", "information security", "infosec",
    "penetration testing", "pentesting", "ethical hacking",
    "vulnerability assessment", "owasp", "owasp top 10",
    "siem", "soc", "threat hunting", "incident response",
    "network security", "firewall", "ids", "ips",
    "encryption", "cryptography", "pki", "ssl", "tls", "https",
    "oauth", "oauth2", "openid connect", "oidc", "saml", "sso",
    "jwt", "api security", "zero trust",
    "secret management", "vault", "aws secrets manager",
    "devsecops", "shift left security", "sast", "dast",
    "dependency scanning", "container scanning", "snyk",
    "compliance", "gdpr", "hipaa", "sox", "pci dss", "iso 27001",
    "identity and access management", "iam", "rbac", "abac",
    "cloud security", "aws security", "azure security",
    "wireshark", "nmap", "burp suite", "metasploit",
    "kali linux", "reverse engineering",

    # ── Mobile ────────────────────────────────────────────────────────────────
    "android", "ios", "react native", "flutter", "dart",
    "swift", "swiftui", "objective-c",
    "kotlin", "jetpack compose", "android studio",
    "xcode", "cocoapods", "swift package manager",
    "expo", "capacitor", "ionic", "cordova",
    "mobile development", "cross-platform",
    "push notifications", "deep linking", "mobile analytics",
    "app store", "google play", "testflight",
    "mobile ui", "mobile ux",

    # ── Agile & Project Management ────────────────────────────────────────────
    "agile", "scrum", "kanban", "lean", "safe",
    "sprint", "sprint planning", "retrospective", "standup",
    "jira", "confluence", "trello", "asana", "monday.com", "linear",
    "notion", "clickup", "basecamp",
    "project management", "product management", "program management",
    "product roadmap", "backlog grooming", "story points",
    "stakeholder management", "risk management", "change management",
    "pmp", "prince2", "csm", "certified scrum master",

    # ── Communication & Soft Skills ───────────────────────────────────────────
    "communication", "teamwork", "collaboration", "leadership",
    "problem solving", "critical thinking", "analytical thinking",
    "time management", "prioritization", "presentation",
    "mentoring", "coaching", "team building",
    "written communication", "verbal communication",
    "cross-functional collaboration", "stakeholder communication",
    "technical writing", "documentation",
    "conflict resolution", "negotiation", "decision making",
    "adaptability", "growth mindset",

    # ── Architecture & Design Patterns ────────────────────────────────────────
    "microservices", "monolithic architecture", "service-oriented architecture",
    "event-driven architecture", "eda", "cqrs", "event sourcing",
    "domain-driven design", "ddd", "clean architecture", "hexagonal architecture",
    "solid principles", "design patterns", "system design",
    "distributed systems", "consensus algorithms", "cap theorem",
    "api design", "api versioning", "backward compatibility",
    "message queue", "message broker", "pub/sub pattern",
    "circuit breaker", "bulkhead", "rate limiting", "throttling",
    "caching", "cdn", "edge computing",
    "high availability", "fault tolerance", "disaster recovery",
    "scalability", "performance optimization", "low latency",
    "uml", "er diagrams", "architecture diagrams",

    # ── Blockchain & Web3 ─────────────────────────────────────────────────────
    "blockchain", "ethereum", "solidity", "web3", "defi",
    "smart contracts", "nft", "ipfs", "hardhat", "foundry", "truffle",
    "web3.js", "ethers.js", "wagmi", "viem",

    # ── Game Development ──────────────────────────────────────────────────────
    "unity", "unreal engine", "godot", "game development",
    "opengl", "vulkan", "directx", "webgl", "three.js", "babylon.js",
    "shader", "hlsl", "glsl",

    # ── Domain-specific ───────────────────────────────────────────────────────
    "finance", "fintech", "banking", "payments", "trading",
    "risk modeling", "quant finance", "algorithmic trading",
    "healthcare", "health tech", "ehr", "fhir", "hl7", "dicom",
    "e-commerce", "retail tech", "marketplace",
    "supply chain", "logistics", "inventory management",
    "erp", "sap", "sap hana", "sap fiori",
    "crm", "salesforce", "salesforce apex", "salesforce lwc",
    "hubspot", "zendesk",
    "edtech", "lms", "learning management system",
    "geospatial", "gis", "arcgis", "mapbox", "leaflet",
    "iot", "internet of things", "mqtt", "modbus",
    "embedded systems", "firmware", "rtos", "arduino", "raspberry pi",
    "robotics", "ros", "ros2",
    "autonomous vehicles", "lidar", "slam",
    "augmented reality", "ar", "virtual reality", "vr", "xr",

    # ── Tools & Productivity ──────────────────────────────────────────────────
    "vs code", "visual studio", "intellij", "pycharm", "eclipse",
    "vim", "neovim", "emacs",
    "slack", "teams", "zoom",
    "figma", "sketch", "adobe xd", "invision",
    "postman", "insomnia",
    "linux terminal", "command line", "cli",
    "ssh", "sftp", "vpn",
    "makefile", "cmake", "gradle", "maven", "bazel", "buck",
    "poetry", "pipenv", "pip", "conda", "uv",
    "npm", "yarn", "pnpm", "bun",
    "cargo", "mix", "leiningen",
    "virtual environment", "docker", "devcontainer",
    "pre-commit", "husky", "lint-staged",

    # ── Protocols & Standards ─────────────────────────────────────────────────
    "tcp/ip", "http", "https", "http2", "http3", "quic",
    "websocket", "server-sent events", "sse", "long polling",
    "grpc", "protobuf", "avro", "parquet", "orc", "json", "xml", "yaml",
    "openapi", "asyncapi", "json schema",
    "oauth2", "jwt", "saml", "ldap", "active directory",
    "dns", "cdn", "tls", "mtls",
]

# ──────────────────────────────────────────────────────────────────────────────
# ROLES
# ──────────────────────────────────────────────────────────────────────────────
ROLES = [
    # Engineering
    "software engineer", "software developer", "software architect",
    "backend developer", "backend engineer",
    "frontend developer", "frontend engineer",
    "full stack developer", "full stack engineer", "full-stack developer",
    "staff engineer", "principal engineer", "distinguished engineer",
    "senior software engineer", "junior software engineer",
    "lead engineer", "tech lead", "engineering manager",

    # Data
    "data analyst", "senior data analyst", "junior data analyst",
    "data scientist", "senior data scientist",
    "data engineer", "senior data engineer",
    "analytics engineer", "bi developer", "bi analyst",
    "business intelligence developer", "business analyst",
    "database administrator", "dba",
    "data architect", "enterprise architect",

    # ML / AI
    "ml engineer", "machine learning engineer", "senior ml engineer",
    "ai engineer", "ai researcher", "research scientist",
    "nlp engineer", "computer vision engineer",
    "mlops engineer", "applied scientist",
    "research engineer", "deep learning engineer",

    # DevOps / Infrastructure
    "devops engineer", "senior devops engineer",
    "cloud engineer", "cloud architect",
    "sre", "site reliability engineer",
    "platform engineer", "infrastructure engineer",
    "systems engineer", "network engineer",
    "solutions architect", "aws solutions architect",

    # Security
    "security engineer", "security analyst",
    "penetration tester", "ethical hacker",
    "information security analyst", "soc analyst",
    "devsecops engineer",

    # Mobile
    "mobile developer", "android developer", "ios developer",
    "react native developer", "flutter developer",

    # QA
    "qa engineer", "quality assurance engineer",
    "test engineer", "automation engineer", "sdet",

    # Product & Design
    "product manager", "senior product manager", "associate product manager",
    "product owner", "program manager",
    "ux designer", "ui designer", "ux/ui designer",
    "product designer", "interaction designer",

    # Management
    "engineering manager", "vp of engineering", "cto",
    "director of engineering", "head of engineering",
    "technical program manager", "tpm",

    # Specialized
    "blockchain developer", "smart contract developer",
    "game developer", "unity developer",
    "embedded systems engineer", "firmware engineer",
    "robotics engineer", "computer vision researcher",
    "quantitative analyst", "quant developer",
    "salesforce developer", "sap developer",
    "ios engineer", "android engineer",
]

# ──────────────────────────────────────────────────────────────────────────────
# EDUCATION KEYWORDS
# ──────────────────────────────────────────────────────────────────────────────
EDUCATION_KEYWORDS = [
    # Bachelor
    "b.tech", "btech", "b.e", "be", "bachelor", "b.sc", "bsc",
    "b.s", "bs", "b.a", "ba", "b.com", "bcom",
    "bachelor of science", "bachelor of engineering", "bachelor of technology",
    "bachelor of arts", "bachelor of commerce",
    "undergraduate", "ug",

    # Master
    "m.tech", "mtech", "m.e", "me", "master", "m.sc", "msc",
    "m.s", "ms", "m.a", "ma", "mba",
    "master of science", "master of engineering", "master of technology",
    "master of business administration", "master of arts",
    "postgraduate", "pg",

    # Doctorate
    "phd", "ph.d", "doctorate", "doctoral", "d.phil",

    # Other
    "associate", "diploma", "certificate", "certification",
    "high school", "secondary", "10+2", "12th",
    "gpa", "cgpa", "grade point", "first class", "distinction", "honors",
]

# ──────────────────────────────────────────────────────────────────────────────
# SECTION KEYWORDS
# ──────────────────────────────────────────────────────────────────────────────
SECTION_KEYWORDS = {
    "skills": [
        "skills", "technical skills", "core competencies", "expertise",
        "tools", "technologies", "tech stack", "technical expertise",
        "key skills", "competencies", "proficiencies", "programming skills",
        "tools and technologies", "skills and technologies",
        "languages and frameworks", "technical proficiencies",
    ],
    "experience": [
        "experience", "work experience", "professional experience",
        "employment", "employment history", "work history",
        "internship", "internships", "career history", "positions held",
        "professional background", "job history", "professional history",
    ],
    "education": [
        "education", "academic background", "qualifications", "academics",
        "educational background", "academic qualifications",
        "degrees", "academic history", "scholastics",
    ],
    "projects": [
        "projects", "personal projects", "academic projects", "key projects",
        "notable projects", "portfolio", "side projects",
        "open source", "contributions", "selected projects",
    ],
    "certifications": [
        "certifications", "certificates", "licenses", "achievements",
        "awards", "accreditations", "professional certifications",
        "credentials", "courses", "training",
    ],
    "summary": [
        "summary", "profile", "objective", "about me",
        "professional summary", "overview", "career objective",
        "executive summary", "career summary", "professional profile",
        "introduction", "bio",
    ],
    "publications": [
        "publications", "papers", "research", "patents",
        "conference papers", "journal articles",
    ],
    "languages": [
        "languages", "spoken languages", "language proficiency",
    ],
    "interests": [
        "interests", "hobbies", "extracurricular", "volunteering",
        "activities",
    ],
}

# ──────────────────────────────────────────────────────────────────────────────
# SKILL SYNONYMS
# ──────────────────────────────────────────────────────────────────────────────
SKILL_SYNONYMS = {

    # ── Python ────────────────────────────────────────────────────────────────
    "py":                            "python",
    "python3":                       "python",
    "python 3":                      "python",
    "python2":                       "python",
    "python 2":                      "python",
    "cpython":                       "python",

    # ── Java ──────────────────────────────────────────────────────────────────
    "java 8":                        "java",
    "java 11":                       "java",
    "java 17":                       "java",
    "java 21":                       "java",
    "core java":                     "java",
    "advanced java":                 "java",
    "j2ee":                          "java",
    "jvm":                           "java",

    # ── JavaScript ────────────────────────────────────────────────────────────
    "js":                            "javascript",
    "es6":                           "javascript",
    "es2015":                        "javascript",
    "es2016":                        "javascript",
    "es2020":                        "javascript",
    "vanilla js":                    "javascript",
    "vanilla javascript":            "javascript",
    "ecmascript":                    "javascript",
    "ts":                            "typescript",

    # ── Go ────────────────────────────────────────────────────────────────────
    "golang":                        "go",
    "go lang":                       "go",
    "go programming":                "go",

    # ── C/C++ ─────────────────────────────────────────────────────────────────
    "cplusplus":                     "c++",
    "cpp":                           "c++",
    "c plus plus":                   "c++",
    "csharp":                        "c#",
    "c sharp":                       "c#",
    "dotnet":                        ".net",
    "dot net":                       ".net",

    # ── Kotlin ────────────────────────────────────────────────────────────────
    "kotlin android":                "kotlin",

    # ── Shell ─────────────────────────────────────────────────────────────────
    "shell":                         "bash",
    "shell script":                  "bash",
    "shell scripting":               "bash",
    "unix scripting":                "bash",
    "linux scripting":               "bash",
    "zsh scripting":                 "bash",

    # ── ML Libraries ──────────────────────────────────────────────────────────
    "scikit learn":                  "scikit-learn",
    "sklearn":                       "scikit-learn",
    "sci-kit learn":                 "scikit-learn",
    "tensorflow 2":                  "tensorflow",
    "tf":                            "tensorflow",
    "tf2":                           "tensorflow",
    "keras tensorflow":              "tensorflow",
    "torch":                         "pytorch",
    "pytorch lightning":             "pytorch",
    "hf":                            "hugging face",
    "huggingface":                   "hugging face",
    "hugging-face":                  "hugging face",
    "transformers library":          "transformers",
    "hf transformers":               "transformers",
    "xgb":                           "xgboost",
    "lgbm":                          "lightgbm",
    "gbm":                           "gradient boosting",
    "gradient boosted trees":        "gradient boosting",
    "gradient boosted machines":     "gradient boosting",
    "gbdt":                          "gradient boosting",

    # ── AI / NLP ──────────────────────────────────────────────────────────────
    "natural language processing":   "nlp",
    "computational linguistics":     "nlp",
    "text analytics":                "nlp",
    "text mining":                   "nlp",
    "ml":                            "machine learning",
    "ml/dl":                         "machine learning",
    "dl":                            "deep learning",
    "cv":                            "computer vision",
    "image recognition":             "computer vision",
    "image classification":          "computer vision",
    "rl":                            "reinforcement learning",
    "gen ai":                        "generative ai",
    "genai":                         "generative ai",
    "generative artificial intelligence": "generative ai",
    "llama index":                   "llamaindex",
    "llama-index":                   "llamaindex",
    "retrieval augmented generation":"rag",
    "retrieval-augmented generation":"rag",
    "large language model":          "llm",
    "large language models":         "llms",
    "foundation model":              "llm",
    "language model":                "llm",
    "gpt model":                     "gpt",
    "openai gpt":                    "gpt",
    "chatgpt":                       "gpt",
    "gpt-4":                         "gpt",
    "gpt-3.5":                       "gpt",
    "prompt design":                 "prompt engineering",
    "prompting":                     "prompt engineering",
    "rag pipeline":                  "rag",
    "knowledge retrieval":           "rag",
    "semantic search":               "vector search",
    "vector similarity search":      "vector search",
    "ann search":                    "vector search",
    "approximate nearest neighbour": "vector search",
    "embedding model":               "embeddings",
    "word embedding":                "word embeddings",
    "sentence embedding":            "sentence embeddings",
    "text embedding":                "embeddings",
    "transfer learning":             "transfer learning",
    "fine tuning":                   "fine-tuning",
    "finetuning":                    "fine-tuning",
    "model finetuning":              "fine-tuning",
    "lora fine tuning":              "lora",
    "low rank adaptation":           "lora",
    "peft finetuning":               "peft",
    "mlflow tracking":               "mlflow",
    "wb":                            "wandb",
    "weights & biases":              "wandb",
    "weights and biases":            "wandb",
    "model monitoring":              "model monitoring",
    "ml monitoring":                 "model monitoring",
    "agentic ai":                    "langchain",
    "ai agents":                     "langchain",

    # ── Data Tools ────────────────────────────────────────────────────────────
    "powerbi":                       "power bi",
    "power-bi":                      "power bi",
    "ms power bi":                   "power bi",
    "microsoft power bi":            "power bi",
    "ms excel":                      "excel",
    "microsoft excel":               "excel",
    "google excel":                  "google sheets",
    "google spreadsheet":            "google sheets",
    "google bigquery":               "bigquery",
    "gcp bigquery":                  "bigquery",
    "amazon redshift":               "redshift",
    "aws redshift":                  "redshift",
    "looker studio":                 "looker",
    "google looker":                 "looker",
    "google data studio":            "looker",
    "apache superset":               "superset",
    "tableau desktop":               "tableau",
    "tableau server":                "tableau",
    "tableau online":                "tableau",
    "pandas dataframe":              "pandas",
    "numpy arrays":                  "numpy",

    # ── Databases ─────────────────────────────────────────────────────────────
    "ms sql":                        "mssql",
    "sql server":                    "mssql",
    "microsoft sql server":          "mssql",
    "t-sql":                         "mssql",
    "tsql":                          "mssql",
    "postgres":                      "postgresql",
    "postgre":                       "postgresql",
    "pg":                            "postgresql",
    "pgsql":                         "postgresql",
    "mysql database":                "mysql",
    "mongo":                         "mongodb",
    "mongo db":                      "mongodb",
    "mongodb atlas":                 "mongodb",
    "elastic":                       "elasticsearch",
    "elastic search":                "elasticsearch",
    "es":                            "elasticsearch",
    "opensearch":                    "elasticsearch",
    "redis cache":                   "redis",
    "oracle database":               "oracle",
    "oracle rdbms":                  "oracle",
    "dynamodb":                      "dynamodb",
    "amazon dynamodb":               "dynamodb",
    "aws dynamodb":                  "dynamodb",
    "firebase firestore":            "firestore",
    "cloud firestore":               "firestore",
    "google firestore":              "firestore",
    "clickhouse db":                 "clickhouse",
    "relational database":           "sql",
    "rdbms":                         "sql",
    "key value store":               "redis",
    "document database":             "mongodb",
    "graph db":                      "graph database",
    "vector db":                     "vector database",
    "pgvector extension":            "pgvector",

    # ── Cloud ─────────────────────────────────────────────────────────────────
    "gcp":                           "google cloud",
    "google cloud platform":         "google cloud",
    "amazon web services":           "aws",
    "amazon aws":                    "aws",
    "aws cloud":                     "aws",
    "microsoft azure":               "azure",
    "azure cloud":                   "azure",
    "az":                            "azure",
    "aws ec2":                       "ec2",
    "amazon ec2":                    "ec2",
    "aws s3":                        "s3",
    "amazon s3":                     "s3",
    "aws lambda":                    "lambda",
    "amazon lambda":                 "lambda",
    "aws sagemaker":                 "sagemaker",
    "amazon sagemaker":              "sagemaker",
    "aws rds":                       "rds",
    "amazon rds":                    "rds",
    "aws ecs":                       "ecs",
    "amazon ecs":                    "ecs",
    "aws eks":                       "eks",
    "amazon eks":                    "eks",
    "google kubernetes engine":      "gke",
    "azure kubernetes service":      "aks",

    # ── DevOps / Containers ───────────────────────────────────────────────────
    "k8s":                           "kubernetes",
    "kube":                          "kubernetes",
    "kubectl":                       "kubernetes",
    "docker container":              "docker",
    "containerization":              "docker",
    "containerisation":              "docker",
    "containers":                    "docker",
    "docker swarm":                  "docker",
    "terraform iac":                 "terraform",
    "tf iac":                        "terraform",
    "infrastructure as code":        "terraform",
    "iac":                           "terraform",
    "ansible playbook":              "ansible",
    "ansible automation":            "ansible",
    "helm chart":                    "helm",
    "helm charts":                   "helm",
    "gh actions":                    "github actions",
    "github action":                 "github actions",
    "gha":                           "github actions",
    "cd/ci":                         "ci/cd",
    "ci cd":                         "ci/cd",
    "ci / cd":                       "ci/cd",
    "continuous integration":        "ci/cd",
    "continuous delivery":           "ci/cd",
    "continuous deployment":         "ci/cd",
    "gitops":                        "argocd",
    "argo cd":                       "argocd",
    "nginx web server":              "nginx",
    "reverse proxy":                 "nginx",
    "load balancer":                 "load balancing",

    # ── APIs ──────────────────────────────────────────────────────────────────
    "rest":                          "rest api",
    "restful":                       "rest api",
    "restful api":                   "rest api",
    "rest apis":                     "rest api",
    "rest services":                 "rest api",
    "http api":                      "rest api",
    "web api":                       "rest api",
    "api development":               "rest api",
    "graphql api":                   "graphql",

    # ── Frontend ──────────────────────────────────────────────────────────────
    "react js":                      "react",
    "react.js":                      "react",
    "reactjs":                       "react",
    "react framework":               "react",
    "react hooks":                   "react",
    "next js":                       "next.js",
    "nextjs":                        "next.js",
    "vue":                           "vue.js",
    "vuejs":                         "vue.js",
    "vue js":                        "vue.js",
    "angular js":                    "angular",
    "angularjs":                     "angular",
    "angular 2+":                    "angular",
    "angular framework":             "angular",
    "node.js":                       "nodejs",
    "node js":                       "nodejs",
    "tailwind":                      "tailwindcss",
    "tailwind css":                  "tailwindcss",
    "material-ui":                   "material ui",

    # ── Backend Frameworks ────────────────────────────────────────────────────
    "django rest framework":         "django",
    "django framework":              "django",
    "flask framework":               "flask",
    "fastapi framework":             "fastapi",
    "spring framework":              "spring",
    "spring boot framework":         "spring boot",
    "laravel framework":             "laravel",
    "rails":                         "ruby on rails",
    "ror":                           "ruby on rails",
    "asp net":                       "asp.net",
    "asp.net core":                  "asp.net",
    "dotnet core":                   ".net core",
    "nest js":                       "nestjs",

    # ── Data Engineering ──────────────────────────────────────────────────────
    "apache spark":                  "spark",
    "spark framework":               "spark",
    "pyspark jobs":                  "pyspark",
    "apache kafka":                  "kafka",
    "kafka streaming":               "kafka",
    "kafka broker":                  "kafka",
    "apache airflow":                "airflow",
    "airflow dags":                  "airflow",
    "apache hadoop":                 "hadoop",
    "apache hive":                   "hive",
    "apache flink":                  "flink",
    "apache beam":                   "apache beam",
    "google dataflow":               "dataflow",
    "databricks platform":           "databricks",
    "delta lake":                    "databricks",
    "dbt models":                    "dbt",
    "data build tool":               "dbt",
    "etl pipeline":                  "etl",
    "elt pipeline":                  "elt",
    "data pipelines":                "data pipeline",
    "data warehousing":              "data warehouse",
    "data lakes":                    "data lake",
    "fivetran ingestion":            "fivetran",
    "airbyte connectors":            "airbyte",

    # ── Testing ───────────────────────────────────────────────────────────────
    "test driven":                   "test driven development",
    "tdd approach":                  "tdd",
    "bdd approach":                  "bdd",
    "behaviour driven":              "bdd",
    "behavior driven":               "bdd",
    "behavior driven development":   "bdd",
    "automated testing":             "test automation",
    "test automation framework":     "test automation",
    "e2e testing":                   "end-to-end testing",
    "end to end testing":            "end-to-end testing",
    "selenium webdriver":            "selenium",
    "cypress testing":               "cypress",
    "playwright testing":            "playwright",
    "jmeter testing":                "jmeter",
    "load testing tools":            "load testing",
    "performance test":              "performance testing",
    "unit test":                     "unit testing",
    "integration test":              "integration testing",

    # ── Security ──────────────────────────────────────────────────────────────
    "infosec":                       "information security",
    "cyber security":                "cybersecurity",
    "pentesting":                    "penetration testing",
    "pentest":                       "penetration testing",
    "ethical hacking":               "penetration testing",
    "web application security":      "owasp",
    "appsec":                        "devsecops",
    "application security":         "devsecops",
    "sca":                           "devsecops",
    "oauth 2.0":                     "oauth2",
    "open id connect":               "openid connect",
    "single sign on":                "sso",
    "json web token":                "jwt",

    # ── Agile ─────────────────────────────────────────────────────────────────
    "agile methodology":             "agile",
    "agile development":             "agile",
    "agile practices":               "agile",
    "scrum methodology":             "scrum",
    "scrum framework":               "scrum",
    "kanban board":                  "kanban",
    "jira boards":                   "jira",
    "jira software":                 "jira",
    "atlassian jira":                "jira",

    # ── Architecture ──────────────────────────────────────────────────────────
    "microservice":                  "microservices",
    "micro services":                "microservices",
    "microservice architecture":     "microservices",
    "event driven":                  "event-driven architecture",
    "event-driven":                  "event-driven architecture",
    "eda":                           "event-driven architecture",
    "domain driven design":          "domain-driven design",
    "clean arch":                    "clean architecture",
    "hexagonal arch":                "hexagonal architecture",
    "ports and adapters":            "hexagonal architecture",
    "solid":                         "solid principles",
    "design pattern":                "design patterns",
    "system design":                 "distributed systems",
    "distributed computing":         "distributed systems",
    "message queue":                 "kafka",
    "mq":                            "message queue",

    # ── Monitoring ────────────────────────────────────────────────────────────
    "elk":                           "elk stack",
    "elastic stack":                 "elk stack",
    "elasticsearch kibana":          "elk stack",
    "prometheus grafana":            "grafana",
    "opentelemetry traces":          "opentelemetry",
    "otel":                          "opentelemetry",
    "distributed tracing":           "opentelemetry",
    "datadog monitoring":            "datadog",
    "new relic monitoring":          "new relic",

    # ── Version Control ───────────────────────────────────────────────────────
    "version control":               "git",
    "source control":                "git",
    "git flow":                      "git",
    "github platform":               "github",
    "gitlab platform":               "gitlab",

    # ── Misc ──────────────────────────────────────────────────────────────────
    "ms powerpoint":                 "presentation",
    "power point":                   "presentation",
    "microsoft powerpoint":          "presentation",
    "ms word":                       "documentation",
    "technical documentation":       "documentation",
    "api docs":                      "documentation",
    "swagger docs":                  "openapi",
    "open api":                      "openapi",
    "grpc protocol":                 "grpc",
    "protocol buffers":              "protobuf",
    "apache avro":                   "avro",
    "apache parquet":                "parquet",
    "json format":                   "json",
    "yaml configuration":            "yaml",
    "linux os":                      "linux",
    "unix":                          "linux",
    "ubuntu linux":                  "linux",
    "debian linux":                  "linux",
    "centos linux":                  "linux",
    "rhel":                          "linux",
    "macos":                         "linux",
    "command line interface":        "cli",
    "terminal":                      "linux terminal",
    "ssh access":                    "ssh",
    "jupyter notebooks":             "jupyter",
    "ipython notebook":              "jupyter",
    "colab":                         "google colab",
    "google colaboratory":           "google colab",
    "vscode":                        "vs code",
    "visual studio code":            "vs code",
    "intellij idea":                 "intellij",
    "pycharm ide":                   "pycharm",
    "figma design":                  "figma",
    "ui design":                     "figma",
    "ux design":                     "figma",
    "restful web services":          "rest api",
    "web services":                  "rest api",
    "http services":                 "rest api",
    "soap services":                 "soap",
    "xml web services":              "soap",
    "message passing":               "message queue",
    "pub sub":                       "kafka",
    "event bus":                     "kafka",
    "stream processing":             "kafka",
    "real time analytics":           "clickhouse",
    "olap engine":                   "clickhouse",
    "column store":                  "clickhouse",
    "caching layer":                 "redis",
    "in-memory cache":               "redis",
    "in memory database":            "redis",
    "session management":            "redis",
    "rate limiting":                 "redis",
    "geospatial data":               "gis",
    "maps api":                      "mapbox",
}